import type { Metadata } from "next";
import { Archivo, Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--f-display",
  display: "swap"
});

const sourceSans3 = Source_Sans_3({
    subsets: ["latin"],
    variable: "--f-body",     // → var(--f-body)
    display: "swap",
  });

  const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    variable: "--f-mono",     // → var(--f-mono)
    display: "swap",
  });

const playfairDisplayHeading = Playfair_Display({subsets:['latin'],variable:'--font-heading'});

const notoSans = Noto_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", archivo.variable, sourceSans3.variable, jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
