import type { Van } from '@/lib/types'

export const VANS: Van[] = [
  {
    id: 'costa',
    name: 'Costa',
    tagline_es: 'La familiar grande',
    tagline_en: 'The family flagship',
    descr_es: 'Espacio para cuatro de verdad. Cama fija arriba, cama doble abajo, baño completo. Para padres que quieren un viaje, no una excursión.',
    descr_en: 'Real room for four. Fixed bed up top, double bed below, full bathroom. For parents who want a trip, not an expedition.',
    perfect_es: ['Familias con dos niños', 'Viajes de 7+ días', 'No te apetece montar la cama cada noche'],
    perfect_en: ['Families with two kids', 'Trips of 7+ days', "You don't want to make the bed every night"],
    not_es: ['Buscas algo ágil para aparcar', 'No tienes carnet C1 o B antiguo'],
    not_en: ['You want something nimble', 'No C1 or pre-1997 B license'],
    sleeps: 4,
    seats: 4,
    license: 'C1',
    length: '6.94 m',
    transmission_es: 'Automático',
    transmission_en: 'Automatic',
    consumption: '8.2 L/100',
    bath: true,
    kitchen: 'full',
    offroad: false,
    base: { name: 'Mercedes-style', kind_es: 'Capuchina grande', kind_en: 'Coachbuilt' },
    price: { low: 110, mid: 125, high: 140 },
    tiers: [
      { d_es: '1 día',         d_en: '1 day',       per: 140 },
      { d_es: '2 días',        d_en: '2 days',      per: 130 },
      { d_es: '3 a 6 días',    d_en: '3 to 6 days', per: 125 },
      { d_es: '7 a 13 días',   d_en: '7 to 13 days',per: 115 },
      { d_es: '14 días o más', d_en: '14+ days',    per: 110 },
    ],
    color: 'terra',
  },
  {
    id: 'sierra',
    name: 'Sierra',
    tagline_es: 'La 4x4 aventurera',
    tagline_en: 'The 4x4 adventurer',
    descr_es: 'Tracción a las cuatro ruedas, suspensión elevada y ducha exterior. Donde acaba el asfalto, ella empieza.',
    descr_en: 'All-wheel drive, raised suspension and an outdoor shower. Where the tarmac ends, she starts.',
    perfect_es: ['Pareja aventurera', 'Pirineos, Picos, Sierra Nevada', 'Acampada libre y pistas forestales'],
    perfect_en: ['Adventurous couple', 'Pyrenees, Picos, Sierra Nevada', 'Wild camping and forest tracks'],
    not_es: ['Vas con niños pequeños', 'Necesitas comodidad de hotel'],
    not_en: ['Travelling with small kids', 'You want hotel-level comfort'],
    sleeps: 2,
    seats: 3,
    license: 'B',
    length: '5.90 m',
    transmission_es: 'Manual',
    transmission_en: 'Manual',
    consumption: '9.1 L/100',
    bath: true,
    kitchen: 'compact',
    offroad: true,
    base: { name: 'Sprinter 4x4', kind_es: 'Camperizada', kind_en: 'Camper conversion' },
    price: { low: 100, mid: 115, high: 130 },
    tiers: [
      { d_es: '1 día',         d_en: '1 day',       per: 130 },
      { d_es: '2 días',        d_en: '2 days',      per: 120 },
      { d_es: '3 a 6 días',    d_en: '3 to 6 days', per: 115 },
      { d_es: '7 a 13 días',   d_en: '7 to 13 days',per: 105 },
      { d_es: '14 días o más', d_en: '14+ days',    per: 100 },
    ],
    color: 'sage',
  },
  {
    id: 'valle',
    name: 'Valle',
    tagline_es: 'La compacta de dos',
    tagline_en: 'The compact two-seater',
    descr_es: 'Aparcas en cualquier sitio. Conduces como un coche. Sin baño a bordo: vives en la calle, duermes dentro.',
    descr_en: "You can park it anywhere. Drives like a car. No on-board bathroom: live outside, sleep inside.",
    perfect_es: ['Pareja jóven', 'Escapada de fin de semana', 'Te vas a campings o áreas con baño'],
    perfect_en: ['Young couple', 'Weekend getaway', "You're going to campsites with bathrooms"],
    not_es: ['Más de dos personas', 'No quieres depender de áreas'],
    not_en: ["More than two people", "You don't want to depend on van areas"],
    sleeps: 2,
    seats: 4,
    license: 'B',
    length: '4.99 m',
    transmission_es: 'Automático',
    transmission_en: 'Automatic',
    consumption: '7.4 L/100',
    bath: false,
    kitchen: 'compact',
    offroad: false,
    base: { name: 'VW California-style', kind_es: 'Camper compacta', kind_en: 'Compact camper' },
    price: { low: 80, mid: 90, high: 100 },
    tiers: [
      { d_es: '1 día',         d_en: '1 day',       per: 100 },
      { d_es: '2 días',        d_en: '2 days',      per: 95  },
      { d_es: '3 a 6 días',    d_en: '3 to 6 days', per: 90  },
      { d_es: '7 a 13 días',   d_en: '7 to 13 days',per: 85  },
      { d_es: '14 días o más', d_en: '14+ days',    per: 80  },
    ],
    color: 'ink',
  },
  {
    id: 'mar',
    name: 'Mar',
    tagline_es: 'La premium de la costa',
    tagline_en: 'The coastal premium',
    descr_es: 'Cocina amplia, ducha de spa, ventanal panorámico para ver el amanecer desde la cama. Para viajes lentos.',
    descr_en: 'Big kitchen, spa-style shower, panoramic window to watch the sunrise from bed. For slow trips.',
    perfect_es: ['Pareja que se mima', "Costa Brava, Algarve, Côte d'Azur", 'Viajes largos y tranquilos'],
    perfect_en: ['Couples who treat themselves', "Costa Brava, Algarve, Côte d'Azur", 'Long, slow trips'],
    not_es: ['Vas con prisa', 'Buscas el precio más bajo'],
    not_en: ["You're in a hurry", "You're looking for the cheapest"],
    sleeps: 2,
    seats: 4,
    license: 'B',
    length: '6.36 m',
    transmission_es: 'Automático',
    transmission_en: 'Automatic',
    consumption: '8.0 L/100',
    bath: true,
    kitchen: 'premium',
    offroad: false,
    base: { name: 'Ducato premium', kind_es: 'Perfilada premium', kind_en: 'Low-profile premium' },
    price: { low: 120, mid: 135, high: 150 },
    tiers: [
      { d_es: '1 día',         d_en: '1 day',       per: 150 },
      { d_es: '2 días',        d_en: '2 days',      per: 140 },
      { d_es: '3 a 6 días',    d_en: '3 to 6 days', per: 135 },
      { d_es: '7 a 13 días',   d_en: '7 to 13 days',per: 125 },
      { d_es: '14 días o más', d_en: '14+ days',    per: 120 },
    ],
    color: 'terra',
  },
]
